<?php

/**
 * @file
 * Contains htaccess_import.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function htaccess_import_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the htaccess_import module.
    case 'help.page.htaccess_import':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A plugin for Redirect module, allows users to import 301 redirects from htaccess file') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function htaccess_import_theme() {
  return [
    'htaccess_import' => [
      'render element' => 'children',
    ],
  ];
}
